### ISSUE TITLE
Add documentation for ZipArchive

### ISSUE THREAD

**Issue by ezeql** [MattRogowski/Plugin-Uploader#2]
Hit this problem. Please Add link to http://stackoverflow.com/questions/18774568/installing-php-zip-extension in documentation for userts/hosts not having the required extension

**Comment by MattRogowski** [comment]
I'm not sure I really wanna start going into explaining how to configure the server - I think it's quite a commonly installed extension, can't think of any other reports of it not being available, and if it's not, could be multiple ways of making it available - may need to be enabled in a control panel, would need to give instructions for every control panel, or if it needs installing on the server, either the host would do it, or if you manage your own server, would probably need to know how to install PHP extensions anyway.
