### ISSUE TITLE
Permission problems while uploading your own plugins within this plugin

### ISSUE THREAD

**Issue by BarbzYHOOL** [MattRogowski/Plugin-Uploader#4]
When I try to install your other plugins with the plugin uploader, it says this:

> It has been detected that your server may not be able to move the plugin files to their proper locations using standard PHP functions. Instead, the Plugin Uploader may need to connect via FTP to move the files.

Or this:

>  There was an error importing this plugin. This plugin has extra files, including language files, that may need to be included in order to run the info function. These files could not be moved to their proper locations:
> 
>     ./inc/languages/english/aamessage.lang.php

What should I do ? I've put chmod 777 on the temp directory of course but it seems like there are other permissions to give.
Though I chmod g+s all the files, before, I don't know if it's related but I doubt it.

**Comment by MattRogowski** [comment]
The first message explains what you'll need to do - PHP does not have permission to copy the files, thus you must use the FTP functionality the plugin offers.

**Comment by BarbzYHOOL** [comment]
Can't, I don't use a classic ftp thing sadly
